// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BgKademliaMessage.proto

package io.hbt.bubblegum.core.kademlia.protobuf;

public final class BgKademliaMessage {
  private BgKademliaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KademliaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string exchangeID = 1;</code>
     */
    java.lang.String getExchangeID();
    /**
     * <code>string exchangeID = 1;</code>
     */
    com.google.protobuf.ByteString
        getExchangeIDBytes();

    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    boolean hasConnectionMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage getConnectionMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder getConnectionMessageOrBuilder();

    /**
     * <code>string padding = 3;</code>
     */
    java.lang.String getPadding();
    /**
     * <code>string padding = 3;</code>
     */
    com.google.protobuf.ByteString
        getPaddingBytes();

    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage}
   */
  public  static final class KademliaMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
      KademliaMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KademliaMessage.newBuilder() to construct.
    private KademliaMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KademliaMessage() {
      exchangeID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KademliaMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              exchangeID_ = s;
              break;
            }
            case 18: {
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder subBuilder = null;
              if (messageCase_ == 2) {
                subBuilder = ((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 2;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              messageCase_ = 3;
              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.class, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.Builder.class);
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      CONNECTIONMESSAGE(2),
      PADDING(3),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 2: return CONNECTIONMESSAGE;
          case 3: return PADDING;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int EXCHANGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object exchangeID_;
    /**
     * <code>string exchangeID = 1;</code>
     */
    public java.lang.String getExchangeID() {
      java.lang.Object ref = exchangeID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeID_ = s;
        return s;
      }
    }
    /**
     * <code>string exchangeID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeIDBytes() {
      java.lang.Object ref = exchangeID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNECTIONMESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    public boolean hasConnectionMessage() {
      return messageCase_ == 2;
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage getConnectionMessage() {
      if (messageCase_ == 2) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder getConnectionMessageOrBuilder() {
      if (messageCase_ == 2) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
    }

    public static final int PADDING_FIELD_NUMBER = 3;
    /**
     * <code>string padding = 3;</code>
     */
    public java.lang.String getPadding() {
      java.lang.Object ref = "";
      if (messageCase_ == 3) {
        ref = message_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (messageCase_ == 3) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string padding = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPaddingBytes() {
      java.lang.Object ref = "";
      if (messageCase_ == 3) {
        ref = message_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (messageCase_ == 3) {
          message_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExchangeIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exchangeID_);
      }
      if (messageCase_ == 2) {
        output.writeMessage(2, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_);
      }
      if (messageCase_ == 3) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExchangeIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exchangeID_);
      }
      if (messageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_);
      }
      if (messageCase_ == 3) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage)) {
        return super.equals(obj);
      }
      io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage other = (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) obj;

      boolean result = true;
      result = result && getExchangeID()
          .equals(other.getExchangeID());
      result = result && getMessageCase().equals(
          other.getMessageCase());
      if (!result) return false;
      switch (messageCase_) {
        case 2:
          result = result && getConnectionMessage()
              .equals(other.getConnectionMessage());
          break;
        case 3:
          result = result && getPadding()
              .equals(other.getPadding());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGEID_FIELD_NUMBER;
      hash = (53 * hash) + getExchangeID().hashCode();
      switch (messageCase_) {
        case 2:
          hash = (37 * hash) + CONNECTIONMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getConnectionMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PADDING_FIELD_NUMBER;
          hash = (53 * hash) + getPadding().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.class, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.Builder.class);
      }

      // Construct using io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exchangeID_ = "";

        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstanceForType() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage build() {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage buildPartial() {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage result = new io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage(this);
        result.exchangeID_ = exchangeID_;
        if (messageCase_ == 2) {
          if (connectionMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = connectionMessageBuilder_.build();
          }
        }
        if (messageCase_ == 3) {
          result.message_ = message_;
        }
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) {
          return mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage other) {
        if (other == io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.getDefaultInstance()) return this;
        if (!other.getExchangeID().isEmpty()) {
          exchangeID_ = other.exchangeID_;
          onChanged();
        }
        switch (other.getMessageCase()) {
          case CONNECTIONMESSAGE: {
            mergeConnectionMessage(other.getConnectionMessage());
            break;
          }
          case PADDING: {
            messageCase_ = 3;
            message_ = other.message_;
            onChanged();
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object exchangeID_ = "";
      /**
       * <code>string exchangeID = 1;</code>
       */
      public java.lang.String getExchangeID() {
        java.lang.Object ref = exchangeID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchangeID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchangeID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExchangeIDBytes() {
        java.lang.Object ref = exchangeID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchangeID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchangeID = 1;</code>
       */
      public Builder setExchangeID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchangeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeID = 1;</code>
       */
      public Builder clearExchangeID() {
        
        exchangeID_ = getDefaultInstance().getExchangeID();
        onChanged();
        return this;
      }
      /**
       * <code>string exchangeID = 1;</code>
       */
      public Builder setExchangeIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchangeID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder> connectionMessageBuilder_;
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public boolean hasConnectionMessage() {
        return messageCase_ == 2;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage getConnectionMessage() {
        if (connectionMessageBuilder_ == null) {
          if (messageCase_ == 2) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 2) {
            return connectionMessageBuilder_.getMessage();
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public Builder setConnectionMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage value) {
        if (connectionMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          connectionMessageBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public Builder setConnectionMessage(
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder builderForValue) {
        if (connectionMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          connectionMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public Builder mergeConnectionMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage value) {
        if (connectionMessageBuilder_ == null) {
          if (messageCase_ == 2 &&
              message_ != io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance()) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.newBuilder((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 2) {
            connectionMessageBuilder_.mergeFrom(value);
          }
          connectionMessageBuilder_.setMessage(value);
        }
        messageCase_ = 2;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public Builder clearConnectionMessage() {
        if (connectionMessageBuilder_ == null) {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 2) {
            messageCase_ = 0;
            message_ = null;
          }
          connectionMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder getConnectionMessageBuilder() {
        return getConnectionMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder getConnectionMessageOrBuilder() {
        if ((messageCase_ == 2) && (connectionMessageBuilder_ != null)) {
          return connectionMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 2) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaConnectionMessage connectionMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder> 
          getConnectionMessageFieldBuilder() {
        if (connectionMessageBuilder_ == null) {
          if (!(messageCase_ == 2)) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.getDefaultInstance();
          }
          connectionMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessageOrBuilder>(
                  (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.KademliaConnectionMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 2;
        onChanged();;
        return connectionMessageBuilder_;
      }

      /**
       * <code>string padding = 3;</code>
       */
      public java.lang.String getPadding() {
        java.lang.Object ref = "";
        if (messageCase_ == 3) {
          ref = message_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (messageCase_ == 3) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string padding = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPaddingBytes() {
        java.lang.Object ref = "";
        if (messageCase_ == 3) {
          ref = message_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (messageCase_ == 3) {
            message_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string padding = 3;</code>
       */
      public Builder setPadding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  messageCase_ = 3;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string padding = 3;</code>
       */
      public Builder clearPadding() {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string padding = 3;</code>
       */
      public Builder setPaddingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        messageCase_ = 3;
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
    }

    // @@protoc_insertion_point(class_scope:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
    private static final io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage();
    }

    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KademliaMessage>
        PARSER = new com.google.protobuf.AbstractParser<KademliaMessage>() {
      @java.lang.Override
      public KademliaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KademliaMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KademliaMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KademliaMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027BgKademliaMessage.proto\022\'io.hbt.bubble" +
      "gum.core.kademlia.protobuf\032!BgKademliaCo" +
      "nnectionMessage.proto\"\244\001\n\017KademliaMessag" +
      "e\022\022\n\nexchangeID\030\001 \001(\t\022_\n\021connectionMessa" +
      "ge\030\002 \001(\0132B.io.hbt.bubblegum.core.kademli" +
      "a.protobuf.KademliaConnectionMessageH\000\022\021" +
      "\n\007padding\030\003 \001(\tH\000B\t\n\007messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.getDescriptor(),
        }, assigner);
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor,
        new java.lang.String[] { "ExchangeID", "ConnectionMessage", "Padding", "Message", });
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaConnectionMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
