// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BgKademliaMessage.proto

package io.hbt.bubblegum.core.kademlia.protobuf;

public final class BgKademliaMessage {
  private BgKademliaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KademliaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Who you are and the context of the message
     * </pre>
     *
     * <code>string exchangeID = 1;</code>
     */
    java.lang.String getExchangeID();
    /**
     * <pre>
     * Who you are and the context of the message
     * </pre>
     *
     * <code>string exchangeID = 1;</code>
     */
    com.google.protobuf.ByteString
        getExchangeIDBytes();

    /**
     * <code>string recipient = 2;</code>
     */
    java.lang.String getRecipient();
    /**
     * <code>string recipient = 2;</code>
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <pre>
     * Who I am
     * </pre>
     *
     * <code>string originNetwork = 3;</code>
     */
    java.lang.String getOriginNetwork();
    /**
     * <pre>
     * Who I am
     * </pre>
     *
     * <code>string originNetwork = 3;</code>
     */
    com.google.protobuf.ByteString
        getOriginNetworkBytes();

    /**
     * <code>string originHash = 4;</code>
     */
    java.lang.String getOriginHash();
    /**
     * <code>string originHash = 4;</code>
     */
    com.google.protobuf.ByteString
        getOriginHashBytes();

    /**
     * <code>string originIP = 5;</code>
     */
    java.lang.String getOriginIP();
    /**
     * <code>string originIP = 5;</code>
     */
    com.google.protobuf.ByteString
        getOriginIPBytes();

    /**
     * <code>int32 originPort = 6;</code>
     */
    int getOriginPort();

    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    boolean hasPingMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing getPingMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder getPingMessageOrBuilder();

    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    boolean hasSyncMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync getSyncMessage();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder getSyncMessageOrBuilder();

    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    boolean hasPayload();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload getPayload();
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder getPayloadOrBuilder();

    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage}
   */
  public  static final class KademliaMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
      KademliaMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KademliaMessage.newBuilder() to construct.
    private KademliaMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KademliaMessage() {
      exchangeID_ = "";
      recipient_ = "";
      originNetwork_ = "";
      originHash_ = "";
      originIP_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KademliaMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              exchangeID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              recipient_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              originNetwork_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              originHash_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              originIP_ = s;
              break;
            }
            case 48: {

              originPort_ = input.readInt32();
              break;
            }
            case 58: {
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder subBuilder = null;
              if (messageCase_ == 7) {
                subBuilder = ((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_).toBuilder();
              }
              message_ =
                  input.readMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 7;
              break;
            }
            case 66: {
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder subBuilder = null;
              if (messageCase_ == 8) {
                subBuilder = ((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_).toBuilder();
              }
              message_ =
                  input.readMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 8;
              break;
            }
            case 74: {
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder subBuilder = null;
              if (messageCase_ == 9) {
                subBuilder = ((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_).toBuilder();
              }
              message_ =
                  input.readMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 9;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.class, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.Builder.class);
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      PINGMESSAGE(7),
      SYNCMESSAGE(8),
      PAYLOAD(9),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 7: return PINGMESSAGE;
          case 8: return SYNCMESSAGE;
          case 9: return PAYLOAD;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int EXCHANGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object exchangeID_;
    /**
     * <pre>
     * Who you are and the context of the message
     * </pre>
     *
     * <code>string exchangeID = 1;</code>
     */
    public java.lang.String getExchangeID() {
      java.lang.Object ref = exchangeID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchangeID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Who you are and the context of the message
     * </pre>
     *
     * <code>string exchangeID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeIDBytes() {
      java.lang.Object ref = exchangeID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchangeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object recipient_;
    /**
     * <code>string recipient = 2;</code>
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      }
    }
    /**
     * <code>string recipient = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINNETWORK_FIELD_NUMBER = 3;
    private volatile java.lang.Object originNetwork_;
    /**
     * <pre>
     * Who I am
     * </pre>
     *
     * <code>string originNetwork = 3;</code>
     */
    public java.lang.String getOriginNetwork() {
      java.lang.Object ref = originNetwork_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originNetwork_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Who I am
     * </pre>
     *
     * <code>string originNetwork = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOriginNetworkBytes() {
      java.lang.Object ref = originNetwork_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originNetwork_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINHASH_FIELD_NUMBER = 4;
    private volatile java.lang.Object originHash_;
    /**
     * <code>string originHash = 4;</code>
     */
    public java.lang.String getOriginHash() {
      java.lang.Object ref = originHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originHash_ = s;
        return s;
      }
    }
    /**
     * <code>string originHash = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOriginHashBytes() {
      java.lang.Object ref = originHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINIP_FIELD_NUMBER = 5;
    private volatile java.lang.Object originIP_;
    /**
     * <code>string originIP = 5;</code>
     */
    public java.lang.String getOriginIP() {
      java.lang.Object ref = originIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originIP_ = s;
        return s;
      }
    }
    /**
     * <code>string originIP = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOriginIPBytes() {
      java.lang.Object ref = originIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINPORT_FIELD_NUMBER = 6;
    private int originPort_;
    /**
     * <code>int32 originPort = 6;</code>
     */
    public int getOriginPort() {
      return originPort_;
    }

    public static final int PINGMESSAGE_FIELD_NUMBER = 7;
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    public boolean hasPingMessage() {
      return messageCase_ == 7;
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing getPingMessage() {
      if (messageCase_ == 7) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder getPingMessageOrBuilder() {
      if (messageCase_ == 7) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
    }

    public static final int SYNCMESSAGE_FIELD_NUMBER = 8;
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    public boolean hasSyncMessage() {
      return messageCase_ == 8;
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync getSyncMessage() {
      if (messageCase_ == 8) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder getSyncMessageOrBuilder() {
      if (messageCase_ == 8) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 9;
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    public boolean hasPayload() {
      return messageCase_ == 9;
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload getPayload() {
      if (messageCase_ == 9) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
    }
    /**
     * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
     */
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder getPayloadOrBuilder() {
      if (messageCase_ == 9) {
         return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_;
      }
      return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getExchangeIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, exchangeID_);
      }
      if (!getRecipientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recipient_);
      }
      if (!getOriginNetworkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, originNetwork_);
      }
      if (!getOriginHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, originHash_);
      }
      if (!getOriginIPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, originIP_);
      }
      if (originPort_ != 0) {
        output.writeInt32(6, originPort_);
      }
      if (messageCase_ == 7) {
        output.writeMessage(7, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_);
      }
      if (messageCase_ == 8) {
        output.writeMessage(8, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_);
      }
      if (messageCase_ == 9) {
        output.writeMessage(9, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExchangeIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, exchangeID_);
      }
      if (!getRecipientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recipient_);
      }
      if (!getOriginNetworkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, originNetwork_);
      }
      if (!getOriginHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, originHash_);
      }
      if (!getOriginIPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, originIP_);
      }
      if (originPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, originPort_);
      }
      if (messageCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_);
      }
      if (messageCase_ == 8) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_);
      }
      if (messageCase_ == 9) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage)) {
        return super.equals(obj);
      }
      io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage other = (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) obj;

      if (!getExchangeID()
          .equals(other.getExchangeID())) return false;
      if (!getRecipient()
          .equals(other.getRecipient())) return false;
      if (!getOriginNetwork()
          .equals(other.getOriginNetwork())) return false;
      if (!getOriginHash()
          .equals(other.getOriginHash())) return false;
      if (!getOriginIP()
          .equals(other.getOriginIP())) return false;
      if (getOriginPort()
          != other.getOriginPort()) return false;
      if (!getMessageCase().equals(other.getMessageCase())) return false;
      switch (messageCase_) {
        case 7:
          if (!getPingMessage()
              .equals(other.getPingMessage())) return false;
          break;
        case 8:
          if (!getSyncMessage()
              .equals(other.getSyncMessage())) return false;
          break;
        case 9:
          if (!getPayload()
              .equals(other.getPayload())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXCHANGEID_FIELD_NUMBER;
      hash = (53 * hash) + getExchangeID().hashCode();
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipient().hashCode();
      hash = (37 * hash) + ORIGINNETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getOriginNetwork().hashCode();
      hash = (37 * hash) + ORIGINHASH_FIELD_NUMBER;
      hash = (53 * hash) + getOriginHash().hashCode();
      hash = (37 * hash) + ORIGINIP_FIELD_NUMBER;
      hash = (53 * hash) + getOriginIP().hashCode();
      hash = (37 * hash) + ORIGINPORT_FIELD_NUMBER;
      hash = (53 * hash) + getOriginPort();
      switch (messageCase_) {
        case 7:
          hash = (37 * hash) + PINGMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getPingMessage().hashCode();
          break;
        case 8:
          hash = (37 * hash) + SYNCMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getSyncMessage().hashCode();
          break;
        case 9:
          hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
          hash = (53 * hash) + getPayload().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.class, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.Builder.class);
      }

      // Construct using io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        exchangeID_ = "";

        recipient_ = "";

        originNetwork_ = "";

        originHash_ = "";

        originIP_ = "";

        originPort_ = 0;

        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstanceForType() {
        return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage build() {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage buildPartial() {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage result = new io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage(this);
        result.exchangeID_ = exchangeID_;
        result.recipient_ = recipient_;
        result.originNetwork_ = originNetwork_;
        result.originHash_ = originHash_;
        result.originIP_ = originIP_;
        result.originPort_ = originPort_;
        if (messageCase_ == 7) {
          if (pingMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = pingMessageBuilder_.build();
          }
        }
        if (messageCase_ == 8) {
          if (syncMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = syncMessageBuilder_.build();
          }
        }
        if (messageCase_ == 9) {
          if (payloadBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = payloadBuilder_.build();
          }
        }
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) {
          return mergeFrom((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage other) {
        if (other == io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage.getDefaultInstance()) return this;
        if (!other.getExchangeID().isEmpty()) {
          exchangeID_ = other.exchangeID_;
          onChanged();
        }
        if (!other.getRecipient().isEmpty()) {
          recipient_ = other.recipient_;
          onChanged();
        }
        if (!other.getOriginNetwork().isEmpty()) {
          originNetwork_ = other.originNetwork_;
          onChanged();
        }
        if (!other.getOriginHash().isEmpty()) {
          originHash_ = other.originHash_;
          onChanged();
        }
        if (!other.getOriginIP().isEmpty()) {
          originIP_ = other.originIP_;
          onChanged();
        }
        if (other.getOriginPort() != 0) {
          setOriginPort(other.getOriginPort());
        }
        switch (other.getMessageCase()) {
          case PINGMESSAGE: {
            mergePingMessage(other.getPingMessage());
            break;
          }
          case SYNCMESSAGE: {
            mergeSyncMessage(other.getSyncMessage());
            break;
          }
          case PAYLOAD: {
            mergePayload(other.getPayload());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object exchangeID_ = "";
      /**
       * <pre>
       * Who you are and the context of the message
       * </pre>
       *
       * <code>string exchangeID = 1;</code>
       */
      public java.lang.String getExchangeID() {
        java.lang.Object ref = exchangeID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchangeID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Who you are and the context of the message
       * </pre>
       *
       * <code>string exchangeID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getExchangeIDBytes() {
        java.lang.Object ref = exchangeID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchangeID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Who you are and the context of the message
       * </pre>
       *
       * <code>string exchangeID = 1;</code>
       */
      public Builder setExchangeID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchangeID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Who you are and the context of the message
       * </pre>
       *
       * <code>string exchangeID = 1;</code>
       */
      public Builder clearExchangeID() {
        
        exchangeID_ = getDefaultInstance().getExchangeID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Who you are and the context of the message
       * </pre>
       *
       * <code>string exchangeID = 1;</code>
       */
      public Builder setExchangeIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchangeID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <code>string recipient = 2;</code>
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string recipient = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string recipient = 2;</code>
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 2;</code>
       */
      public Builder clearRecipient() {
        
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 2;</code>
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recipient_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object originNetwork_ = "";
      /**
       * <pre>
       * Who I am
       * </pre>
       *
       * <code>string originNetwork = 3;</code>
       */
      public java.lang.String getOriginNetwork() {
        java.lang.Object ref = originNetwork_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originNetwork_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Who I am
       * </pre>
       *
       * <code>string originNetwork = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOriginNetworkBytes() {
        java.lang.Object ref = originNetwork_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originNetwork_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Who I am
       * </pre>
       *
       * <code>string originNetwork = 3;</code>
       */
      public Builder setOriginNetwork(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originNetwork_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Who I am
       * </pre>
       *
       * <code>string originNetwork = 3;</code>
       */
      public Builder clearOriginNetwork() {
        
        originNetwork_ = getDefaultInstance().getOriginNetwork();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Who I am
       * </pre>
       *
       * <code>string originNetwork = 3;</code>
       */
      public Builder setOriginNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originNetwork_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object originHash_ = "";
      /**
       * <code>string originHash = 4;</code>
       */
      public java.lang.String getOriginHash() {
        java.lang.Object ref = originHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string originHash = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOriginHashBytes() {
        java.lang.Object ref = originHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originHash = 4;</code>
       */
      public Builder setOriginHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originHash = 4;</code>
       */
      public Builder clearOriginHash() {
        
        originHash_ = getDefaultInstance().getOriginHash();
        onChanged();
        return this;
      }
      /**
       * <code>string originHash = 4;</code>
       */
      public Builder setOriginHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object originIP_ = "";
      /**
       * <code>string originIP = 5;</code>
       */
      public java.lang.String getOriginIP() {
        java.lang.Object ref = originIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string originIP = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOriginIPBytes() {
        java.lang.Object ref = originIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originIP = 5;</code>
       */
      public Builder setOriginIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originIP = 5;</code>
       */
      public Builder clearOriginIP() {
        
        originIP_ = getDefaultInstance().getOriginIP();
        onChanged();
        return this;
      }
      /**
       * <code>string originIP = 5;</code>
       */
      public Builder setOriginIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originIP_ = value;
        onChanged();
        return this;
      }

      private int originPort_ ;
      /**
       * <code>int32 originPort = 6;</code>
       */
      public int getOriginPort() {
        return originPort_;
      }
      /**
       * <code>int32 originPort = 6;</code>
       */
      public Builder setOriginPort(int value) {
        
        originPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 originPort = 6;</code>
       */
      public Builder clearOriginPort() {
        
        originPort_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder> pingMessageBuilder_;
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public boolean hasPingMessage() {
        return messageCase_ == 7;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing getPingMessage() {
        if (pingMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
        } else {
          if (messageCase_ == 7) {
            return pingMessageBuilder_.getMessage();
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public Builder setPingMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing value) {
        if (pingMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          pingMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public Builder setPingMessage(
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder builderForValue) {
        if (pingMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          pingMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public Builder mergePingMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing value) {
        if (pingMessageBuilder_ == null) {
          if (messageCase_ == 7 &&
              message_ != io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance()) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.newBuilder((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 7) {
            pingMessageBuilder_.mergeFrom(value);
          }
          pingMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public Builder clearPingMessage() {
        if (pingMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
          }
          pingMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder getPingMessageBuilder() {
        return getPingMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder getPingMessageOrBuilder() {
        if ((messageCase_ == 7) && (pingMessageBuilder_ != null)) {
          return pingMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 7) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaPing pingMessage = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder> 
          getPingMessageFieldBuilder() {
        if (pingMessageBuilder_ == null) {
          if (!(messageCase_ == 7)) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.getDefaultInstance();
          }
          pingMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPingOrBuilder>(
                  (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.KademliaPing) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 7;
        onChanged();;
        return pingMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder> syncMessageBuilder_;
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public boolean hasSyncMessage() {
        return messageCase_ == 8;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync getSyncMessage() {
        if (syncMessageBuilder_ == null) {
          if (messageCase_ == 8) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
        } else {
          if (messageCase_ == 8) {
            return syncMessageBuilder_.getMessage();
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public Builder setSyncMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync value) {
        if (syncMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          syncMessageBuilder_.setMessage(value);
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public Builder setSyncMessage(
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder builderForValue) {
        if (syncMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          syncMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public Builder mergeSyncMessage(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync value) {
        if (syncMessageBuilder_ == null) {
          if (messageCase_ == 8 &&
              message_ != io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance()) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.newBuilder((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 8) {
            syncMessageBuilder_.mergeFrom(value);
          }
          syncMessageBuilder_.setMessage(value);
        }
        messageCase_ = 8;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public Builder clearSyncMessage() {
        if (syncMessageBuilder_ == null) {
          if (messageCase_ == 8) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 8) {
            messageCase_ = 0;
            message_ = null;
          }
          syncMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder getSyncMessageBuilder() {
        return getSyncMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder getSyncMessageOrBuilder() {
        if ((messageCase_ == 8) && (syncMessageBuilder_ != null)) {
          return syncMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 8) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSync syncMessage = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder> 
          getSyncMessageFieldBuilder() {
        if (syncMessageBuilder_ == null) {
          if (!(messageCase_ == 8)) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.getDefaultInstance();
          }
          syncMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSyncOrBuilder>(
                  (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.KademliaSync) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 8;
        onChanged();;
        return syncMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder> payloadBuilder_;
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public boolean hasPayload() {
        return messageCase_ == 9;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload getPayload() {
        if (payloadBuilder_ == null) {
          if (messageCase_ == 9) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
        } else {
          if (messageCase_ == 9) {
            return payloadBuilder_.getMessage();
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public Builder setPayload(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }
        messageCase_ = 9;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public Builder setPayload(
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 9;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public Builder mergePayload(io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload value) {
        if (payloadBuilder_ == null) {
          if (messageCase_ == 9 &&
              message_ != io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance()) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.newBuilder((io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 9) {
            payloadBuilder_.mergeFrom(value);
          }
          payloadBuilder_.setMessage(value);
        }
        messageCase_ = 9;
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          if (messageCase_ == 9) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 9) {
            messageCase_ = 0;
            message_ = null;
          }
          payloadBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder getPayloadBuilder() {
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder getPayloadOrBuilder() {
        if ((messageCase_ == 9) && (payloadBuilder_ != null)) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 9) {
            return (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_;
          }
          return io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
        }
      }
      /**
       * <code>.io.hbt.bubblegum.core.kademlia.protobuf.KademliaSealedPayload payload = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          if (!(messageCase_ == 9)) {
            message_ = io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.getDefaultInstance();
          }
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload.Builder, io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayloadOrBuilder>(
                  (io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.KademliaSealedPayload) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 9;
        onChanged();;
        return payloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
    }

    // @@protoc_insertion_point(class_scope:io.hbt.bubblegum.core.kademlia.protobuf.KademliaMessage)
    private static final io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage();
    }

    public static io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KademliaMessage>
        PARSER = new com.google.protobuf.AbstractParser<KademliaMessage>() {
      @java.lang.Override
      public KademliaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KademliaMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KademliaMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KademliaMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaMessage.KademliaMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027BgKademliaMessage.proto\022\'io.hbt.bubble" +
      "gum.core.kademlia.protobuf\032\024BgKademliaPi" +
      "ng.proto\032\035BgKademliaSealedPayload.proto\032" +
      "\024BgKademliaSync.proto\"\203\003\n\017KademliaMessag" +
      "e\022\022\n\nexchangeID\030\001 \001(\t\022\021\n\trecipient\030\002 \001(\t" +
      "\022\025\n\roriginNetwork\030\003 \001(\t\022\022\n\noriginHash\030\004 " +
      "\001(\t\022\020\n\010originIP\030\005 \001(\t\022\022\n\noriginPort\030\006 \001(" +
      "\005\022L\n\013pingMessage\030\007 \001(\01325.io.hbt.bubblegu" +
      "m.core.kademlia.protobuf.KademliaPingH\000\022" +
      "L\n\013syncMessage\030\010 \001(\01325.io.hbt.bubblegum." +
      "core.kademlia.protobuf.KademliaSyncH\000\022Q\n" +
      "\007payload\030\t \001(\0132>.io.hbt.bubblegum.core.k" +
      "ademlia.protobuf.KademliaSealedPayloadH\000" +
      "B\t\n\007messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.getDescriptor(),
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.getDescriptor(),
          io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.getDescriptor(),
        }, assigner);
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_hbt_bubblegum_core_kademlia_protobuf_KademliaMessage_descriptor,
        new java.lang.String[] { "ExchangeID", "Recipient", "OriginNetwork", "OriginHash", "OriginIP", "OriginPort", "PingMessage", "SyncMessage", "Payload", "Message", });
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaPing.getDescriptor();
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSealedPayload.getDescriptor();
    io.hbt.bubblegum.core.kademlia.protobuf.BgKademliaSync.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
